export const API_CALL_BEGIN = "BEGIN_API_CALL";

export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";

export const UPDATE_REVIEW_SUCCESS = "UPDATE_REVIEW_SUCCESS";

export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";

export const API_CALL_ERROR = "API_CALL_ERROR";

//
//
export const LOAD_REVIEWS_SUCCESS = "LOAD_REVIEWS_SUCCESS";
